### ISSUE TITLE
Not receiving messages 

### ISSUE THREAD

**Issue by nmarcetic** [mainflux/mqtt-adapter#11]
Since the last changes with protobuf integration I am not receiving messages any more. I am subscribed to same channel with same client_token and I am not getting published messages. 
I tested with mqtt -> mqtt and also publishing from http , reading from mqtt.

**Comment by drasko** [comment]
Very important: same mosquitto client can not be at the same SUB and do the PUB on the same topic - Aedes will do the disconnection of SUB in order to do PUB, so client will not receive message when he re-subscribes.

Please use different clients (devices).
